; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
extra_configs =
    platformio.envs/*.ini

[env]
framework = arduino
; platform = https://github.com/pioarduino/platform-espressif32.git#55.03.38-1
platform = https://github.com/pioarduino/platform-espressif32.git#55.03.39

monitor_speed = 3000000

; flash settings for 4MB flash, which is the size of the flash chips on the PCBs (see esp32-s3-devkitc-1 datasheet)
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_upload.flash_size = 4MB
board_build.partitions = min_spiffs.csv

; global build flags applied to *all* envs
build_unflags =
    -DARDUINO_USB_CDC_ON_BOOT=0
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=0
	-DARDUINO_USB_MODE=1
	-Os
build_flags =
    ;-UCONFIG_ESP_TIMER_SOURCE_APB ;disable APB clock source and use xtal clock source instead as timer callbacks and wifi seem to interfere 
    ;-DCONFIG_ESP_TIMER_SOURCE_XTAL=1
    -DARDUINO_USB_MODE=0 ; 0: UsbOTG (zwingend für TinyUSB HID Joystick)
    -DARDUINO_USB_CDC_ON_BOOT=0 ; 0: Mappt "Serial" auf Hardware UART0 (CP2102), anstatt auf Native USB
	;-Ddouble=float
	;-mforce-fp32
	-DARDUINO_RUNNING_CORE=0 ; run on core 0 (communication core) do not interfere the pedal update task, for smooth pedal feeling
	-O3 # compiler optimization for runtime 
	-ffast-math                      ; Erlaubt dem Compiler performantere FPU-Befehle (bricht strikte IEEE-Konformität, genial für DSP/Regler)
    -fno-exceptions                  ; Schaltet C++ Exceptions ab (spart Flash und Overhead)
    -fno-rtti                        ; Schaltet Runtime Type Information ab
    -DCORE_DEBUG_LEVEL=0             ; Schaltet alle ESP-Logs komplett ab
	
extra_scripts = 
	pre:../CommonResources/update_version.py
	post:../CommonResources/copy_boot_app0.py

[common]
lib_deps_external = 
	https://github.com/ChrGri/FastNonAccelStepper.git
	https://github.com/RobTillaart/FastTrig.git
	CubicInterpolatorFloat=symlink://../Common_Libs/CubicInterpolatorFloat
	DiyActivePedal_types=symlink://../Common_Libs/DiyActivePedal_types
	TaskScheduler=symlink://../Common_Libs/TaskScheduler
	MovingAverageFilter=symlink://../Common_Libs/MovingAverageFilter
