#pragma once
typedef enum PedalStatus
{
  PEDAL_STATUS_NORMAL,
  PEDAL_STATUS_RUDDER,
  PEDAL_STATUS_RUDDERBRAKE
} PedalStatus_t;

typedef enum PedalId
{
  PEDAL_ID_CLUTCH,
  PEDAL_ID_BRAKE,
  PEDAL_ID_THROTTLE,
  PEDAL_ID_ASSIGNMENT_ERROR,
  PEDAL_ID_UNKNOWN,
  PEDAL_ID_TEMP_1,
  PEDAL_ID_TEMP_2,
  PEDAL_ID_TEMP_3
} PedalId_t;

enum class PedalSystemAction
{
  NONE,
  RESET_PEDAL_POSITION, // not in use
  PEDAL_RESTART,
  ENABLE_OTA,     // not in use
  ENABLE_PAIRING, // not in use
  ESP_BOOT_INTO_DOWNLOAD_MODE,
  PRINT_PEDAL_INFO,
  SET_ASSIGNMENT_0,
  SET_ASSIGNMENT_1,
  SET_ASSIGNMENT_2,
  CLEAR_ASSIGNMENT,
  ASSIGNMENT_CHECK_BEEP,
  WAKEUP_PEDAL
};

using PedalSystemAction_t = PedalSystemAction;

enum class RudderAction
{
  NONE,
  RUDDER_THROTTLE_AND_BRAKE,
  RUDDER_CLEAR_RUDDER_STATUS,
  RUDDER_THROTTLE_AND_CLUTCH,
  HELIRUDDER_THROTTLE_AND_BRAKE,
  HELIRUDDER_THROTTLE_AND_CLUTCH
};

using RudderAction_t = RudderAction;

typedef enum BridgeAction
{
  BRIDGE_ACTION_NONE,
  BRIDGE_ACTION_ENABLE_PAIRING,
  BRIDGE_ACTION_RESTART,
  BRIDGE_ACTION_DOWNLOAD_MODE,
  BRIDGE_ACTION_DEBUG,
  BRIDGE_ACTION_JOYSTICK_FLASHING_MODE,
  BRIDGE_ACTION_JOYSTICK_DEBUG,
  BRIDGE_ACTION_SET_PEDAL_WIRELESS_SYNC
} BridgeAction_t;

typedef enum OtaAction
{
  OTA_ACTION_NORMAL,
  OTA_ACTION_FORCE_UPDATE,
  OTA_ACTION_PLATFORMIO_DIRECT_UPLOAD,
  OTA_ACTION_ESP_BOOT_INTO_DOWNLOAD_MODE
} OtaAction_t;